### ISSUE TITLE
推荐使用opencv下的 腾讯的二维码识别模型进行二维码识别

### ISSUE THREAD

**Issue by mrkaria** [tomorinao-www/nonebot-plugin-qrcode2#1]
可以对AI画图二维码进行识别
![image](https://github.com/tomorinao-www/nonebot-plugin-qrcode2/assets/41931603/ef89db6d-bee1-4939-819f-b83363c4d27f)

**Comment by tomorinao-www** [comment]
我自己试的不太行，麻烦给一下你这个bot插件的地址，我去抄一抄

**Comment by tomorinao-www** [comment]
> 可以对AI画图二维码进行识别 ![image](https://user-images.githubusercontent.com/41931603/266839074-ef89db6d-bee1-4939-819f-b83363c4d27f.png)

我自己试的不太行，麻烦给一下你这个bot插件的地址，我去抄一抄

**Comment by mrkaria** [comment]
腾讯的二维码识别模型：https://github.com/WeChatCV/opencv_3rdparty
核心就这些，整体写的太烂了🥲
![image](https://github.com/tomorinao-www/nonebot-plugin-qrcode2/assets/41931603/17ca0fbf-b084-4aed-b72d-57e86511bb4d)
opencv版本可以参考我这个
opencv-contrib-python                 4.7.0.72
opencv-python                         4.7.0.72
python-opencv                         1.0.0.14

**Comment by tomorinao-www** [comment]
测试通过，明天更新
